import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ICloudBackground from "@/app/components/ICloudBackground";
import Navbar from "@/app/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio of Tharindu Dulaj",
  description: "Generated by create next app",
  icons: {
    icon: "/icon-t.svg",
    shortcut: "/icon-t.svg",
    apple: "/icon-t.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ICloudBackground />
        <Navbar />
        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}
